// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrdemServicoAspNetMVC.Models;

namespace OrdemServicoAspNetMVC.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20210810001230_base-inicial")]
    partial class baseinicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OrdemServicoAspNetMVC.Models.OrdemServico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataFechamento")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("idColaborador")
                        .HasColumnType("int");

                    b.Property<int>("idDefeitoIdentificado")
                        .HasColumnType("int");

                    b.Property<int>("idDefeitoReclamado")
                        .HasColumnType("int");

                    b.Property<int>("idSolucaoAplicada")
                        .HasColumnType("int");

                    b.Property<int>("idTipoContrato")
                        .HasColumnType("int");

                    b.Property<int>("idTipoServico")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("Id");

                    b.ToTable("ordensServicos");
                });
#pragma warning restore 612, 618
        }
    }
}
